server:
  port: 22000
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
  mvc:
    throw-exception-if-no-handler-found: true
  resources: 
    add-mappings: false
  datasource:    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/SpringBootMybatisBase?useSSL=false&serverTimezone=GMT%2b8&useJDBCCompliantTimezoneShift=true
    username: zzq
    password: zzq520
logging:
  pattern:
    console: '%d{HH:MM:ss,SSS} [%-5level]  %logger{36}%n \t%msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss,SSS} [%-5level] %logger{36}%n \t%msg%n' 
  #file: logs/springbase.log
  level:
    top:
      wfzzq: debug
mybatis:  config-location: classpath:mybatis-config.xml     